# models.py
from sqlalchemy import Column, Integer, Float, String, DateTime
from .database import Base, engine_2
from sqlalchemy.orm import declarative_base

# Live Measurement Model
class LiveMeasurement(Base):
    __tablename__ = "LiveSheet$"

    SERIAL = Column(String(255), primary_key=True, index=True)
    NAME = Column(String(255))
    LATITUDE = Column(Float)
    LONGITUDE = Column(Float)
    DATETIME = Column(DateTime)
    HEADING = Column(Float)
    RSRP = Column(Float, name="BESTS.RSRP")
    SINR = Column(Float, name="BESTS.SNR")
    TEMP = Column(Float, name="BESTS.TEMP.")
    EARFCN = Column(Integer, name="BESTS.EARFCN")
    BAND = Column(Float, name="BESTS.BAND")
    PCI = Column(Integer, name="BESTS.PCI")
    A_USED= Column(Integer, name="BESTS.SECT#")
    CID= Column(Integer, name="BESTS.CID_dec")
    RSRQ= Column(Integer, name="BESTS.RSRQ")
    NODE_ID= Column(Float, name="BESTS_NODEB_dec")
    SECTOR_ID= Column(Integer, name="SECTORID")
    S0_EARFCN = Column(Float, name="S0.EARFCN")
    S0_BAND = Column(Float, name="S0.BAND")
    S0_CID = Column(Float, name="S0.CID_dec")
    S0_PCI = Column(Float, name="S0.PCI")
    S0_eCID = Column(Float, name="S0.NODEB_dec")
    S0_RSRP = Column(Float, name="S0.RSRP")
    S0_RSRQ = Column(Float, name="S0.RSRQ")
    S0_SINR = Column(Float, name="SECT0.SNR")
    S1_EARFCN = Column(Float, name="S1.EARFCN")
    S1_BAND = Column(Float, name="S1.BAND")
    S1_CID = Column(Float, name="S1.CID_dec")
    S1_PCI = Column(Float, name="S1.PCI")
    S1_eCID = Column(Float, name="S1.NODEB_dec")
    S1_RSRP = Column(Float, name="S1.RSRP")
    S1_RSRQ = Column(Float, name="S1.RSRQ")
    S1_SINR = Column(Float, name="SECT1.SNR")
    S2_EARFCN = Column(Float, name="S2.EARFCN")
    S2_BAND = Column(Float, name="S2.BAND")
    S2_CID = Column(Float, name="S2.CID_dec")
    S2_PCI = Column(Float, name="S2.PCI")
    S2_eCID = Column(Float, name="S2.NODEB_dec")
    S2_RSRP = Column(Float, name="S2.RSRP")
    S2_RSRQ = Column(Float, name="S2.RSRQ")
    S2_SINR = Column(Float, name="SECT2.SNR")
    S3_EARFCN = Column(Float, name="S3.EARFCN")
    S3_BAND = Column(Float, name="S3.BAND")
    S3_CID = Column(Float, name="S3.CID_dec")
    S3_PCI = Column(Float, name="S3.PCI")
    S3_eCID = Column(Float, name="S3.NODEB_dec")
    S3_RSRP = Column(Float, name="S3.RSRP")
    S3_RSRQ = Column(Float, name="S3.RSRQ")
    S3_SINR = Column(Float, name="SECT3.SNR")



############################# SAMPLE OF ANOTHER MODEL #############################

# class CellInfo(Base):
#     __tablename__ = "CellInfo$"

#     SERIAL = Column(String(255), primary_key=True, index=True)
#     PCI = Column(Integer)
#     EARFCN = Column(Integer)
#     TAC = Column(Integer)
#     CI = Column(Integer)
#     BAND = Column(String(50))
#     MCC = Column(Integer)
#     MNC = Column(Integer)

# Historic Measurement Model
class HistoricMeasurement(Base):
    __tablename__ = "HistoricNewConfiguration$"

    SERIAL = Column(String(255), primary_key=True, index=True)
    NAME = Column(String(255))
    LATITUDE = Column(Float)
    LONGITUDE = Column(Float)
    DATETIME = Column(DateTime)
    HEADING = Column(Float)
    SPEED = Column(Float)
    RSRP = Column(Float, name="BESTS.RSRP")
    SINR = Column(Float, name="BESTS.SNR")
    TEMP = Column(Float, name="BESTS.TEMP.")
    S0RSRP = Column(Float, name="S0.RSRP")
    S0SINR = Column(Float, name="SECT0.SNR")
    S1RSRP = Column(Float, name="S1.RSRP")
    S1SINR = Column(Float, name="SECT1.SNR")
    S2RSRP = Column(Float, name="S2.RSRP")
    S2SINR = Column(Float, name="SECT2.SNR")
    S3RSRP = Column(Float, name="S3.RSRP")
    S3SINR = Column(Float, name="SECT3.SNR")
    SELECTED_ANTENNA = Column(Float, name="BESTS.SECT#")
    EARFCN = Column(Float, name="BESTS.EARFCN")
    BEST_CELLID = Column(String(255), name="BESTS.CID_dec")
    BEST_ENBID = Column(String(255), name="BESTS_NODEB_dec")
    BEST_SECID = Column(String(255), name="SECTORID")
    BEST_PCI = Column(String(255), name="BESTS.PCI")
    RSRQ = Column(Float, name="BESTS.RSRQ")
    S0EARFCN = Column(Float, name="S0.EARFCN")
    S0CELLID = Column(String(255), name="S0.CID_dec")
    S0ENBID = Column(String(255), name="S0.NODEB_dec")
    S0PCI = Column(String(255), name="S0.PCI")
    S0RSRQ = Column(Float, name="S0.RSRQ")
    S1EARFCN = Column(Float, name="S1.EARFCN")
    S1CELLID = Column(String(255), name="S1.CID_dec")
    S1ENBID = Column(String(255), name="S1.NODEB_dec")
    S1PCI = Column(String(255), name="S1.PCI")
    S1RSRQ = Column(Float, name="S1.RSRQ")
    S2EARFCN = Column(Float, name="S2.EARFCN")
    S2CELLID = Column(String(255), name="S2.CID_dec")
    S2ENBID = Column(String(255), name="S2.NODEB_dec")
    S2PCI = Column(String(255), name="S2.PCI")
    S2RSRQ = Column(Float, name="S2.RSRQ")
    S3EARFCN = Column(Float, name="S3.EARFCN")
    S3CELLID = Column(String(255), name="S3.CID_dec")
    S3ENBID = Column(String(255), name="S3.NODEB_dec")
    S3PCI = Column(String(255), name="S3.PCI")
    S3RSRQ = Column(Float, name="S3.RSRQ")

# ==================== SECOND DATABASE SOURCE ====================

# Declarative base for second database
Base2 = declarative_base()

# Real-time Probes Measurement Model (Second Database)
class RealTimeProbeMeasurement(Base2):
    __tablename__ = "LiveSheet$"

    SERIAL = Column(String(255), primary_key=True, index=True, name="SN")
    NAME = Column(String(255), name="Name")
    SCAN = Column(Float, name="Scan#")
    GNSS = Column(Float)
    MOBILITY = Column(Float)
    LATITUDE = Column(Float, name="Latitude")
    LONGITUDE = Column(Float, name="Longitude")
    DATETIME = Column(DateTime)
    HEADING = Column(Float, name="Heading")
    SPEED = Column(Float, name="Speed")
    TEMP = Column(Float, name="Temperature")
    LINETYPE = Column(String(255), name="LineType")
    BAND = Column(String(255), name="Band")
    NETEXIST = Column(Float, name="NetExist?")
    REGISTERED = Column(Float, name="Registered?")
    MCC = Column(Float)
    MNC = Column(Float)
    RSRP = Column(Float, name="RSRP dBm")
    RSRQ = Column(Integer, name="RSRQ dB")
    SINR = Column(Float, name="SNIR dB")
    TEMP = Column(Float, name="Temperature")
    EARFCN = Column(String(255))
    PCI = Column(String(255))
    CID = Column(String(255), name="CELL ID")
    CID_DEC = Column(String(255), name="CELL ID DECIMAL")
    TAC = Column(String(255))
    HTTP_KBPS = Column(Float, name="HTTP kbps")
    PING_RTT = Column(Float, name="PING RTT ms")
    BW_DL = Column(Float, name="BW DL")
    BW_UL = Column(Float, name="BW UL")

    # Probes Historic Measurement Model
class ProbesHistoricMeasurement(Base2):
    __tablename__ = "Historic"

    SERIAL = Column(String(255), primary_key=True, index=True, name="SN")
    NAME = Column(String(255), name="Name")
    SCAN = Column(Float, name="Scan#")
    GNSS = Column(Float)
    MOBILITY = Column(Float)
    LATITUDE = Column(Float, name="Latitude")
    LONGITUDE = Column(Float, name="Longitude")
    DATETIME = Column(DateTime)
    HEADING = Column(Float, name="Heading")
    SPEED = Column(Float, name="Speed")
    TEMP = Column(Float, name="Temperature")
    LINETYPE = Column(String(255), name="LineType")
    BAND = Column(String(255), name="Band")
    NETEXIST = Column(Float, name="NetExist?")
    REGISTERED = Column(Float, name="Registered?")
    MCC = Column(Float)
    MNC = Column(Float)
    RSRP = Column(Float, name="RSRP dBm")
    RSRQ = Column(Integer, name="RSRQ dB")
    SINR = Column(Float, name="SNIR dB")
    EARFCN = Column(String(255))
    PCI = Column(String(255))
    CID = Column(String(255), name="CELL ID")
    CID_DEC = Column(String(255), name="CELL ID DECIMAL")
    TAC = Column(String(255))
    HTTP_KBPS = Column(Float, name="HTTP kbps")
    PING_RTT = Column(Float, name="PING RTT ms")
    BW_DL = Column(Float, name="BW DL")
    BW_UL = Column(Float, name="BW UL")
